name: Deploy static site to Azure Web App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'VictoriaCifuentes'   # nombre exacto de tu App Service
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_26E0049417EF44F99E71ED5E9C6B8947 }}
          package: '.'                    # despliega todo lo de la raíz
